sudo: false
language: python
dist: xenial
python:
  - 2.7
  - 3.7
env:
  - IMP_BRANCH=develop
  - IMP_BRANCH=master
cache:
  pip: true
install:
  - source support/setup_travis.sh $HOME/miniconda $IMP_BRANCH $TRAVIS_PYTHON_VERSION
  - python -V
  - export IMP_TMP_DIR=/tmp
script:
  - cd modules/foo
  - mkdir build
  - cd build
  - PYTHON_INC=$(echo $(dirname $(which python))/../include/python*/)
  - cmake .. -DIMP_DIR=${CONDA_PREFIX}/lib/cmake/IMP -DPYTHON_INCLUDE_DIR=$PYTHON_INC -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage"
  - make
  - ./setup_environment.sh ../test/nosetests --with-coverage --cover-branches -e 'probabilistic' ../test/test_*.py test/*/*.py > /dev/null
after_script:
  - bash <(curl -s https://codecov.io/bash)
