.PHONY: clean cleaner

all:
	python3 ../support/tutorial_tools/notebook/process_notebook.py coding

clean:
	rm -f coding.md Doxyfile
	rm -rf html

cleaner:
	rm -f coding.ipynb coding.md Doxyfile
	rm -rf html
